# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'labels', 'examples', 'type_of_guy', 'predict']

# %% ../app.ipynb 3
from fastai.vision.all import *

# %% ../app.ipynb 4
learn = load_learner('export.pkl')

# %% ../app.ipynb 5
def type_of_guy(model):
    return{
        'ascent': 'soccer mom',
        'brz': 'soccer mom',
        'crosstrek': 'lists hiking as their hobby. never hikes',
        'EPX': 'Japanese defense force',
        'forester': 'coexist sticker',
        'not': 'not a subi :(',
        'outback': 'climbing gym',
        'wrx': 'monster energy'
        }.get(model, 'error')
        

# %% ../app.ipynb 6
labels = learn.dls.vocab
def predict(img):
    img = PILImage.create(img)
    pred,pred_idx,probs = learn.predict(img)
    return {type_of_guy(labels[i]): float(probs[i]) for i in range(len(labels))}

# %% ../app.ipynb 7
examples = ['Bell_412.jpg','Ferrari.jpg','WRX.jpg','Crosstrek.jpg']

# %% ../app.ipynb 8
import gradio as gr
gr.Interface(fn=predict, inputs=gr.inputs.Image(shape=(512, 512)), outputs=gr.outputs.Label(num_top_classes=1),examples=examples).launch()
